sonar.projectKey=Melato15_cidadao-ativo-frontend
sonar.projectName=cidadao-ativo-frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=src
sonar.host.url=https://sonarcloud.io
sonar.token=9878905890f635a55e22be9adcdca73ddfc6041a
sonar.organization=melato15

# Padrões de arquivos de teste
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts

# Excluir testes da análise de código fonte (para não duplicar)
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/node_modules/**,**/coverage/**,**/dist/**

# Cobertura de testes
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/test/**,**/*.d.ts,**/next.config.mjs,**/tailwind.config.js,**/postcss.config.js
  